apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloworld-gke
  labels:
    app: hello
  annotations:
    tshirt-size: 'small' # kpt-set: ${tshirt-size}
    new-annotation: 'something'
spec:
  replicas: 5
  selector:
    matchLabels:
      app: hello
  template:
    metadata:
      labels:
        app: hello
    spec:
      containers:
      - name: helloworld-gke
        image: gcr.io/kpt-dev/helloworld-gke:0.1.0
        ports:
        - name: http
          containerPort: 80
        env:
        - name: PORT
          value: "80"
        resources:
          requests:
            cpu: 200m
            memory: 50M
---
apiVersion: v1
kind: Service
metadata:
  name: helloworld-gke
  labels:
    app: hello
spec:
  type: LoadBalancer
  selector:
    app: hello
  ports:
  - protocol: TCP
    port: 80
    targetPort: http
